namespace SWEndor 
{ 
  //This file is auto generated by prebuild.bat 
  public static class Build 
  { 
    public static string Time = "Tue 12/24/2019 22:36:07.37"; 
    public static string BuildDate = "20191224"; 
    public static string Revision = "07"; 
  } 
} 
