namespace SWEndor 
{ 
  //This file is auto generated by prebuild.bat 
  public static class Build 
  { 
    public static string Time = "Sun 12/29/2019 21:44:20.14"; 
    public static string BuildDate = "20191229"; 
    public static string Revision = "07"; 
  } 
} 
