namespace SWEndor 
{ 
  //This file is auto generated by prebuild.bat 
  public static class Build 
  { 
    public static string Time = "Sun 12/29/2019 20:22:25.37"; 
    public static string BuildDate = "20191229"; 
    public static string Revision = "05"; 
  } 
} 
