using System.Reflection; 
using System.Runtime.InteropServices; 

//This file is auto generated by prebuild.bat 
[assembly: AssemblyTitle("SWEndor.Core")] 
[assembly: AssemblyDescription("")] 
[assembly: AssemblyConfiguration("")] 
[assembly: AssemblyCompany("")] 
[assembly: AssemblyProduct("SWEndor.Core")] 
[assembly: AssemblyCopyright("Copyright ? 2019-2023. All rights reserved.")] 
[assembly: AssemblyTrademark("")] 
[assembly: AssemblyCulture("")] 

[assembly: ComVisible(false)] 
[assembly: AssemblyVersion("0.0.*")] 
[assembly: AssemblyFileVersion("0.0.02324.2100")] 

