using System.Reflection; 
using System.Runtime.InteropServices; 
using System.Runtime.CompilerServices; 

//This file is auto generated by prebuild.bat 
[assembly: AssemblyTitle("SWEndor.Core")] 
[assembly: AssemblyConfiguration("")] 
[assembly: AssemblyCompany("")] 
[assembly: AssemblyProduct("SWEndor.Core")] 
[assembly: AssemblyCopyright("Copyright ? 2017-2020. All rights reserved.")] 
[assembly: AssemblyTrademark("")] 
[assembly: AssemblyCulture("")] 

[assembly: ComVisible(false)] 
[assembly: AssemblyVersion("0.0.*")] 
[assembly: AssemblyFileVersion("0.0.02006.2902")] 

//Debug 
#if DEBUG 
[assembly: InternalsVisibleTo("SWEndorTest")] 
#endif 
