namespace SWEndor
{
  public enum ColorLocalKeys
  {
    TRANSPARENT,
    WHITE,

    SYSTEM_FATAL,
    SYSTEM_FATAL_BACKGROUND,
    UI_BACKGROUND_DARK,

    UI_TEXT,
    UI_TEXT_ORANGE,
    UI_TEXT_GOOD,
    UI_TEXT_BAD,
    UI_UNHIGHLIGHT_BACKGROUND,
    UI_UNHIGHLIGHT_DARK_BACKGROUND,
    UI_HIGHLIGHT_BACKGROUND,
    UI_HIGHLIGHT_SELECT_BACKGROUND,

    GAME_LOAD_LIGHT,
    GAME_LOAD_DARK,

    GAME_MAP_GRID_MAJOR,
    GAME_MAP_GRID_MINOR,
    GAME_MAP_BACKGROUND,

    GAME_STAT_SPEED,
    GAME_STAT_SHIELD,
    GAME_STAT_CRITICAL_ALLY,
    GAME_STAT_CRITICAL_ENEMY,

    GAME_MESSAGE_NORMAL,
    GAME_MESSAGE_WARNING,
    GAME_MESSAGE_BACKGROUND,
    GAME_MESSAGE_MISSILE_WARNING_1,
    GAME_MESSAGE_MISSILE_WARNING_2,

    GAME_SYSTEMSTATE_ACTIVE,
    GAME_SYSTEMSTATE_ACTIVE_DAMAGED,
    GAME_SYSTEMSTATE_DISABLED,
    GAME_SYSTEMSTATE_DAMAGED,
    GAME_SYSTEMSTATE_NULL,

    GAME_SYSTEM_ION,
    GAME_SYSTEM_DISABLED,
    GAME_SYSTEM_DESTROYED,

  }
}
