language: csharp
solution: SWEndor.sln
install:
  - sudo apt install xmlstarlet  
  - cd ./src
  - echo "Removing Pre-build events.."
  - find $TRAVIS_BUILD_DIR -type f -iname "*.csproj" -exec sh -c 'xmlstarlet ed --inplace -d "(/_:Project/_:PropertyGroup/_:PreBuildEvent)[1]/.." "{}"' \;
  - echo "Removing Post-build events.."
  - find $TRAVIS_BUILD_DIR -type f -iname "*.csproj" -exec sh -c 'xmlstarlet ed --inplace -d "(/_:Project/_:PropertyGroup/_:PostBuildEvent)[1]/.." "{}"' \;
  - nuget restore SWEndor.sln
script:
  - msbuild /p:Configuration=Debug SWEndor.sln
  - cd ../unittest
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe Primrose.UnitTests.dll
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe Primrose.Expressions.UnitTests.dll
