language: csharp
solution: SWEndor.sln
install:
  - cd ./src
  - nuget restore SWEndor.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Debug SWEndor.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./unittest/Primrose.UnitTests.dll
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./unittest/Primrose.Expressions.UnitTests.dll
