# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

resources:
   repositories:
   - repository: Primrose
     type: git
     name: Primrose/Primrose

trigger:
- master

pool:
  name: selfhost

variables:
  solution: 'SWEndor/src/SWEndor.sln'
  buildPlatform: 'x86'
  buildConfiguration: 'Release'

steps:
- checkout: Primrose

- checkout: self

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
