namespace SWEndor.Core 
{ 
  //This file is auto generated by prebuild.bat 
  public static class Build 
  { 
    public static string Time = "Tue 01/06/2021 19:51:22.59"; 
    public static string BuildDate = "20210106"; 
    public static string Revision = "00"; 
  } 
} 
