namespace SWEndor.Core 
{ 
  //This file is auto generated by prebuild.bat 
  /// <summary>Provides internal build information for this project</summary> 
  public static class Build 
  { 
   /// <summary>The time of build</summary> 
   public const string Time = "Mon 23/10/2023  2:09:47.98"; 
   /// <summary>The date of build in YYYYMMDD format</summary> 
   public const string BuildDate = "20232302"; 
   /// <summary>The daily revision number of the build</summary> 
   public const string Revision = "00"; 
  } 
} 
