@echo off
echo Run prebuild...
set TITLE=SWEndor.Core
set MAJORVERSION=0
set MINORVERSION=0

set ASMYINFO_CS=Properties\AssemblyInfo.cs
set BUILD_CS=Build.cs

set VERSIONBAT=version
set TEMPBAT=temp
set TEMPDATEBAT=tempd
del %TEMPBAT% 2>nul

:: use WMIC to get time instead of locale-dependent %DATE%
:: 20221105173838.183000
wmic os get LocalDateTime|findstr ^^[0-9] >%TEMPDATEBAT%
for /f %%a in (%TEMPDATEBAT%) do set dt=%%a
set YYYY=%dt:~0,4%
set MM=%dt:~6,2%
set DD=%dt:~8,2%
set BUILDDATE=%YYYY%%MM%%DD%
echo %BUILDDATE%
del %TEMPDATEBAT%

set REVISION=0
set NEWDATE=0

setlocal EnableDelayedExpansion
if exist %VERSIONBAT% (
  for /f "tokens=1,2 delims== " %%a in (%VERSIONBAT%) do (
    if %%a==MAJORVERSION (
      set MAJORVERSION=%%b
    ) else if %%a==MINORVERSION (
      set MINORVERSION=%%b
    ) else if %%a==REVISION (
      if not !NEWDATE!==1 (
        set /a REVISION=%%b+1
      )
    ) else if %%a==BUILDDATE (
      if not %%b==%BUILDDATE% (
        set REVISION=0
        set NEWDATE=1
      )
    )
  )
)

if %REVISION% lss 10 set REVISION=0%REVISION%

echo MAJORVERSION=%MAJORVERSION% > %TEMPBAT%
echo MINORVERSION=%MINORVERSION% >> %TEMPBAT%
echo BUILDDATE=%BUILDDATE% >> %TEMPBAT%
echo REVISION=%REVISION% >> %TEMPBAT%

set VERSION=%MAJORVERSION%.%MINORVERSION%.%BUILDDATE%.%REVISION%
set MSVERSION=%MAJORVERSION%.%MINORVERSION%.*
set MSFILEVERSION=%MAJORVERSION%.%MINORVERSION%.%YYYY:~1,3%%MM%.%DD%%REVISION%
echo %VERSION%

attrib -r %BUILD_CS%
echo namespace %TITLE% > %BUILD_CS%
echo { >> %BUILD_CS%
echo   //This file is auto generated by %~nx0 >> %BUILD_CS%
echo   /// ^<summary^>Provides internal build information for this project^</summary^> >> %BUILD_CS%
echo   public static class Build >> %BUILD_CS%
echo   { >> %BUILD_CS%
echo    /// ^<summary^>The time of build^</summary^> >> %BUILD_CS%
echo    public const string Time = "%DATE% %TIME%"; >> %BUILD_CS%
echo    /// ^<summary^>The date of build in YYYYMMDD format^</summary^> >> %BUILD_CS%
echo    public const string BuildDate = "%BUILDDATE%"; >> %BUILD_CS%
echo    /// ^<summary^>The daily revision number of the build^</summary^> >> %BUILD_CS%
echo    public const string Revision = "%REVISION%"; >> %BUILD_CS%
echo   } >> %BUILD_CS%
echo } >> %BUILD_CS%

attrib -r %ASMYINFO_CS%

echo using System.Reflection; > %ASMYINFO_CS%
echo using System.Runtime.InteropServices; >> %ASMYINFO_CS%
echo.>> %ASMYINFO_CS%
echo //This file is auto generated by %~nx0 >> %ASMYINFO_CS%
echo [assembly: AssemblyTitle("%TITLE%")] >> %ASMYINFO_CS%
echo [assembly: AssemblyDescription("")] >> %ASMYINFO_CS%
echo [assembly: AssemblyConfiguration("")] >> %ASMYINFO_CS%
echo [assembly: AssemblyCompany("")] >> %ASMYINFO_CS%
echo [assembly: AssemblyProduct("%TITLE%")] >> %ASMYINFO_CS%
echo [assembly: AssemblyCopyright("Copyright ? 2019-%YYYY%. All rights reserved.")] >> %ASMYINFO_CS%
echo [assembly: AssemblyTrademark("")] >> %ASMYINFO_CS%
echo [assembly: AssemblyCulture("")] >> %ASMYINFO_CS%
echo.>> %ASMYINFO_CS%
echo [assembly: ComVisible(false)] >> %ASMYINFO_CS%
echo [assembly: AssemblyVersion("%MSVERSION%")] >> %ASMYINFO_CS%
echo [assembly: AssemblyFileVersion("%MSFILEVERSION%")] >> %ASMYINFO_CS%
echo.>> %ASMYINFO_CS%

echo Version files updated!