using System.Reflection; 
using System.Runtime.InteropServices; 
using System.Runtime.CompilerServices; 

//This file is auto generated by prebuild.bat 
[assembly: AssemblyTitle("SWEndor")] 
[assembly: AssemblyConfiguration("")] 
[assembly: AssemblyCompany("")] 
[assembly: AssemblyProduct("SWEndor")] 
[assembly: AssemblyCopyright("Copyright © 2017-2019. All rights reserved.")] 
[assembly: AssemblyTrademark("")] 
[assembly: AssemblyCulture("")] 

[assembly: ComVisible(false)] 
[assembly: AssemblyVersion("0.0.*")] 
[assembly: AssemblyFileVersion("0.0.01912.2907")] 

//Debug 
#if DEBUG 
[assembly: InternalsVisibleTo("SWEndorTest")] 
#endif 
