using System.Reflection; 
using System.Runtime.InteropServices; 
using System.Runtime.CompilerServices; 

//This file is auto generated by prebuild.bat 
[assembly: AssemblyTitle("SWEndor")] 
[assembly: AssemblyConfiguration("")] 
[assembly: AssemblyCompany("Nguoi You Jie")]
[assembly: AssemblyProduct("SWEndor")] 
[assembly: AssemblyCopyright("Copyright © 2017-2020. All rights reserved.")] 
[assembly: AssemblyTrademark("")] 
[assembly: AssemblyCulture("")] 

[assembly: ComVisible(false)] 
[assembly: AssemblyVersion("0.1.*")] 
[assembly: AssemblyFileVersion("0.1.0.0")]
[assembly: AssemblyDescription("Recreation of a simple 3D space-combat sim")]

//Debug 
#if DEBUG
[assembly: InternalsVisibleTo("SWEndorTest")] 
#endif
