namespace SWEndor.Core 
{ 
  //This file is auto generated by prebuild.bat 
  public static class Build 
  { 
    public static string Time = "Wed 06/10/2020  9:49:53.48"; 
    public static string BuildDate = "20200610"; 
    public static string Revision = "05"; 
  } 
} 
