namespace SWEndor.Core 
{ 
  //This file is auto generated by prebuild.bat 
  public static class Build 
  { 
    public static string Time = "Mon 06/29/2020 19:24:15.25"; 
    public static string BuildDate = "20200629"; 
    public static string Revision = "02"; 
  } 
} 
