namespace SWEndor.Core 
{ 
  //This file is auto generated by prebuild.bat 
  public static class Build 
  { 
    public static string Time = "Sun 02/23/2020  2:58:18.94"; 
    public static string BuildDate = "20200223"; 
    public static string Revision = "01"; 
  } 
} 
