
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerMethodGroupAllocationRule:Delegate allocation from a method group", Justification = "<Pending>")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "External module will not be changed", Scope = "type", Target = "~T:FMOD.System")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerBoxingRule:Value type to reference type conversion allocation for string concatenation", Justification = "External module will not be changed", Scope = "type", Target = "~T:FMOD.System")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerBoxingRule:Value type to reference type conversion causing boxing allocation", Justification = "External module will not be changed", Scope = "type", Target = "~T:FMOD.System")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.Sound.SoundManager.Piece.Parser.Parse(SWEndor.FileFormat.INI.INIFile,System.String)~SWEndor.Sound.SoundManager.Piece")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerBoxingRule:Value type to reference type conversion allocation for string concatenation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.Sound.SoundManager.Piece.Parser.Parse(SWEndor.FileFormat.INI.INIFile,System.String)~SWEndor.Sound.SoundManager.Piece")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerClosureSourceRule:Closure Allocation Source", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.Game.Run")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerImplicitParamsRule:Array allocation for params parameter", Justification = "<Pending>", Scope = "member", Target = "~F:SWEndor.Globals.Version")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerBoxingRule:Value type to reference type conversion causing boxing allocation", Justification = "<Pending>", Scope = "member", Target = "~F:SWEndor.Globals.Version")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerBoxingRule:Value type to reference type conversion allocation for string concatenation", Justification = "<Pending>", Scope = "member", Target = "~F:SWEndor.Scenarios.Scripting.Expressions.Ops.binaryops")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.ActorTypes.Components.MeshData.#ctor(System.String,System.String,System.String)")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.ActorTypes.ActorTypeInfo.LoadFromINI")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.Sound.SoundManager.Piece.UpdateSound")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerImplicitParamsRule:Array allocation for params parameter", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.Scenarios.Scripting.Expressions.EvalException.#ctor(SWEndor.Scenarios.Scripting.Expressions.ITracker,System.String,SWEndor.Scenarios.Scripting.Expressions.Val,SWEndor.Scenarios.Scripting.Expressions.Val,System.Exception)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerImplicitParamsRule:Array allocation for params parameter", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.Scenarios.Scripting.Expressions.EvalException.#ctor(SWEndor.Scenarios.Scripting.Expressions.ITracker,System.String,SWEndor.Scenarios.Scripting.Expressions.Val,System.Exception)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerImplicitParamsRule:Array allocation for params parameter", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.Scenarios.Scripting.Expressions.ParseException.#ctor(SWEndor.Scenarios.Scripting.Expressions.Lexer)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerImplicitParamsRule:Array allocation for params parameter", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.Scenarios.Scripting.Expressions.ParseException.#ctor(SWEndor.Scenarios.Scripting.Expressions.Lexer,SWEndor.Scenarios.Scripting.Expressions.TokenEnum)")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerBoxingRule:Value type to reference type conversion causing boxing allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.Scenarios.Scripting.Expressions.EvalException.#ctor(SWEndor.Scenarios.Scripting.Expressions.ITracker,System.String,SWEndor.Scenarios.Scripting.Expressions.Val,SWEndor.Scenarios.Scripting.Expressions.Val,System.Exception)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerBoxingRule:Value type to reference type conversion causing boxing allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.Scenarios.Scripting.Expressions.EvalException.#ctor(SWEndor.Scenarios.Scripting.Expressions.ITracker,System.String,SWEndor.Scenarios.Scripting.Expressions.Val,System.Exception)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerBoxingRule:Value type to reference type conversion causing boxing allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.Scenarios.Scripting.Expressions.ParseException.#ctor(SWEndor.Scenarios.Scripting.Expressions.Lexer)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerBoxingRule:Value type to reference type conversion causing boxing allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.Scenarios.Scripting.Expressions.ParseException.#ctor(SWEndor.Scenarios.Scripting.Expressions.Lexer,SWEndor.Scenarios.Scripting.Expressions.TokenEnum)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerValueTypeNonOverridenCallRule:Non-overridden virtual method call on value type", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.Scenarios.Scripting.Expressions.ParseException.#ctor(SWEndor.Scenarios.Scripting.Expressions.Lexer,SWEndor.Scenarios.Scripting.Expressions.TokenEnum)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerValueTypeNonOverridenCallRule:Non-overridden virtual method call on value type", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.UI.Menu.Pages.KeyboardControls.LoadBindings")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerValueTypeNonOverridenCallRule:Non-overridden virtual method call on value type", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.UI.Menu.Pages.KeyboardControls.SelectToggleCameraMode(MTV3D65.CONST_TV_KEY)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerValueTypeNonOverridenCallRule:Non-overridden virtual method call on value type", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.UI.Menu.Pages.KeyboardControls.SelectToggleDecreaseSpeed(MTV3D65.CONST_TV_KEY)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerValueTypeNonOverridenCallRule:Non-overridden virtual method call on value type", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.UI.Menu.Pages.KeyboardControls.SelectToggleIncreaseSpeed(MTV3D65.CONST_TV_KEY)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerValueTypeNonOverridenCallRule:Non-overridden virtual method call on value type", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.UI.Menu.Pages.KeyboardControls.SelectToggleNextPrimaryWeaponMode(MTV3D65.CONST_TV_KEY)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerValueTypeNonOverridenCallRule:Non-overridden virtual method call on value type", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.UI.Menu.Pages.KeyboardControls.SelectToggleNextSecondaryWeaponMode(MTV3D65.CONST_TV_KEY)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerValueTypeNonOverridenCallRule:Non-overridden virtual method call on value type", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.UI.Menu.Pages.KeyboardControls.SelectTogglePrevPrimaryWeaponMode(MTV3D65.CONST_TV_KEY)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerValueTypeNonOverridenCallRule:Non-overridden virtual method call on value type", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.UI.Menu.Pages.KeyboardControls.SelectTogglePrevSecondaryWeaponMode(MTV3D65.CONST_TV_KEY)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerValueTypeNonOverridenCallRule:Non-overridden virtual method call on value type", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.UI.Menu.Pages.KeyboardControls.SelectToggleRadar(MTV3D65.CONST_TV_KEY)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerValueTypeNonOverridenCallRule:Non-overridden virtual method call on value type", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.UI.Menu.Pages.KeyboardControls.SelectToggleScenarioInfo(MTV3D65.CONST_TV_KEY)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerValueTypeNonOverridenCallRule:Non-overridden virtual method call on value type", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.UI.Menu.Pages.KeyboardControls.SelectToggleScoreboard(MTV3D65.CONST_TV_KEY)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerValueTypeNonOverridenCallRule:Non-overridden virtual method call on value type", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.UI.Menu.Pages.KeyboardControls.SelectToggleUI(MTV3D65.CONST_TV_KEY)~System.Boolean")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerBoxingRule:Value type to reference type conversion causing boxing allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.Settings.SaveSettings(SWEndor.Engine)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerBoxingRule:Value type to reference type conversion causing boxing allocation", Justification = "<Pending>", Scope = "member", Target = "~P:SWEndor.Scenarios.Scripting.Expressions.Val.Value")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~F:SWEndor.Scenarios.Scripting.Expressions.Ops.binaryops")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerValueTypeNonOverridenCallRule:Non-overridden virtual method call on value type", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.AI.Actions.Hunt.ToString~System.String")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerValueTypeNonOverridenCallRule:Non-overridden virtual method call on value type", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.Scenarios.Scripting.Functions.Actor.Squadron_Spawn(SWEndor.Scenarios.Scripting.Expressions.Context,SWEndor.Scenarios.Scripting.Expressions.Val[])~SWEndor.Scenarios.Scripting.Expressions.Val")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.Game.Tick")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.Shaders.ShaderInfo.#ctor(SWEndor.Core.Engine,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.Shaders.ShaderInfo.GenerateShader~MTV3D65.TVShader")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.ActorTypes.Components.AddOnData.SaveToINI(SWEndor.FileFormat.INI.INIFile,System.String,System.String,System.String,SWEndor.ActorTypes.Components.AddOnData[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.ActorTypes.ActorTypeInfo.LoadFromINI(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.ActorTypes.ActorTypeInfo.SaveToINI(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.ExplosionTypes.ExplosionTypeInfo.SaveToINI(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.ExplosionTypes.ExplosionTypeInfo.LoadFromINI(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.Scenarios.GSEndor.#ctor(SWEndor.Scenarios.GameScenarioManager)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.ActorTypes.Components.MeshData.#ctor(System.String,System.String,System.String,System.Single,MTV3D65.CONST_TV_BLENDINGMODE,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.Sound.SoundManager.InstAddSyncPoint.Process(SWEndor.Sound.SoundManager)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.Terminal.TConsole.Execute(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.FileFormat.INI.INIFile.INISection.GetLine(System.String)~SWEndor.FileFormat.INI.INIFile.INISection.INILine")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~P:Primrose.Primitives.Factories.AFactoryObject.ID")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.ProjectileTypes.ProjectileTypeInfo.SaveToINI(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.Scenarios.Scripting.Expressions.TokenTypes.Expressions.Function.Evaluate(SWEndor.Scenarios.Scripting.Expressions.Context)~SWEndor.Scenarios.Scripting.Expressions.Val")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.Sound.SoundManager.Load")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.AtmosphereInfo.LoadDefaults(System.Boolean,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.FileFormat.INI.INIFile.SetStringValue(System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.ActorTypes.Components.DebrisSpawnerData.SaveToINI(SWEndor.FileFormat.INI.INIFile,System.String,System.String,SWEndor.ActorTypes.Components.DebrisSpawnerData[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.ActorTypes.Components.SoundSourceData.SaveToINI(SWEndor.FileFormat.INI.INIFile,System.String,System.String,System.String,SWEndor.ActorTypes.Components.SoundSourceData[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.Core.Session.Tick")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.Models.ExplodeData.SaveToINI(SWEndor.FileFormat.INI.INIFile,System.String,System.String,System.String,SWEndor.Models.ExplodeData[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.ProjectileTypes.ProjectileTypeInfo.LoadFromINI(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.UI.Menu.Pages.LoadingScenario.PrintLoadingText~System.String")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerBoxingRule:Value type to reference type conversion causing boxing allocation", Justification = "Val performs casting without boxing", Scope = "type", Target = "~T:SWEndor.Scenarios.Scripting.Functions.ActorFns")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerBoxingRule:Value type to reference type conversion causing boxing allocation", Justification = "Val performs casting without boxing", Scope = "type", Target = "~T:SWEndor.Scenarios.Scripting.Functions.AIFns")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerBoxingRule:Value type to reference type conversion causing boxing allocation", Justification = "Val performs casting without boxing", Scope = "type", Target = "~T:SWEndor.Scenarios.Scripting.Functions.AudioFns")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerBoxingRule:Value type to reference type conversion causing boxing allocation", Justification = "Val performs casting without boxing", Scope = "type", Target = "~T:SWEndor.Scenarios.Scripting.Functions.FactionFns")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerBoxingRule:Value type to reference type conversion causing boxing allocation", Justification = "Val performs casting without boxing", Scope = "type", Target = "~T:SWEndor.Scenarios.Scripting.Functions.GameFns")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerBoxingRule:Value type to reference type conversion causing boxing allocation", Justification = "Val performs casting without boxing", Scope = "type", Target = "~T:SWEndor.Scenarios.Scripting.Functions.MessagingFns")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerBoxingRule:Value type to reference type conversion causing boxing allocation", Justification = "Val performs casting without boxing", Scope = "type", Target = "~T:SWEndor.Scenarios.Scripting.Functions.MiscFns")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerBoxingRule:Value type to reference type conversion causing boxing allocation", Justification = "Val performs casting without boxing", Scope = "type", Target = "~T:SWEndor.Scenarios.Scripting.Functions.PlayerCameraFns")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerBoxingRule:Value type to reference type conversion causing boxing allocation", Justification = "Val performs casting without boxing", Scope = "type", Target = "~T:SWEndor.Scenarios.Scripting.Functions.PlayerFns")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerBoxingRule:Value type to reference type conversion causing boxing allocation", Justification = "Val performs casting without boxing", Scope = "type", Target = "~T:SWEndor.Scenarios.Scripting.Functions.SceneFns")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerBoxingRule:Value type to reference type conversion causing boxing allocation", Justification = "Val performs casting without boxing", Scope = "type", Target = "~T:SWEndor.Scenarios.Scripting.Functions.ScoreFns")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerBoxingRule:Value type to reference type conversion causing boxing allocation", Justification = "Val performs casting without boxing", Scope = "type", Target = "~T:SWEndor.Scenarios.Scripting.Functions.ScriptingFns")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerBoxingRule:Value type to reference type conversion causing boxing allocation", Justification = "Val performs casting without boxing", Scope = "type", Target = "~T:SWEndor.Scenarios.Scripting.Functions.UIFns")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.ActorTypes.Components.LookData.SaveToINI(SWEndor.FileFormat.INI.INIFile,System.String,System.String,System.String,SWEndor.ActorTypes.Components.LookData[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:SWEndor.PerfManager.PrintPerf")]

